spring.application.name=Digital Banking
#spring.datasource.url=jdbc:h2:mem:bank
#spring.h2.console.enabled=true
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/E-BANK?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

jwt.secret=8fQ2mZ9xLkT7vP3rW6sD1nB5cY0hJ4uA8eR9tG2pK6xM1vN3qS7dF5zC0wL8jH2mX4nQ7pR1sT9uV